<x-layouts.admin title="Complaint History">
    <section class="page-heading">
        <p class="eyebrow">Administration</p>
        <h1>Complaint history</h1>
        <p>Read-only audit records generated by complaint operations.</p>
    </section>
    <section class="content-card filter-card">
        <form method="get" class="admin-filter-form">
            <label for="complaint_id">Complaint ID</label>
            <input id="complaint_id" name="complaint_id" type="number" min="1" value="{{ $filters['complaintId'] }}">
            <input name="action" maxlength="50" placeholder="Action" value="{{ $filters['action'] }}">
            <input name="performer" maxlength="100" placeholder="Performer" value="{{ $filters['performer'] }}">
            <select name="sort">
                <option value="created_at">Date</option>
                <option value="complaint_id" @selected($filters['sort'] === 'complaint_id')>Complaint</option>
            </select>
            <select name="order">
                <option value="desc">Newest</option>
                <option value="asc" @selected($filters['order'] === 'asc')>Oldest</option>
            </select>
            <button type="submit"><x-icon name="filter" /> Filter</button>
            <a href="{{ route('admin.history.index') }}"><x-icon name="x" /> Clear</a>
        </form>
    </section>
    <p class="list-meta">{{ $history->total() }} history entries, page {{ $history->currentPage() }} of {{ $history->lastPage() }}</p>
    @if ($history->isEmpty())
        <section class="content-card empty-state"><h2>No history found</h2><p>No audit records match this filter.</p></section>
    @else
        <section class="content-card table-card"><div class="table-wrapper"><table>
            <thead><tr><th>Complaint</th><th>Action</th><th>Performed by</th><th>Status change</th><th>Assignment change</th><th>Description</th><th>Timestamp</th></tr></thead>
            <tbody>
                @foreach ($history as $entry)
                    <tr>
                        <td>#{{ $entry->complaint_id }}</td>
                        <td>{{ $entry->action }}</td>
                        <td>{{ $entry->performer->name }}</td>
                        <td>{{ $entry->old_status ?? 'none' }} to {{ $entry->new_status ?? 'none' }}</td>
                        <td>{{ $entry->assignedFromUser->name ?? 'Unassigned' }} to {{ $entry->assignedToUser->name ?? 'Unassigned' }}</td>
                        <td>{{ $entry->description }}</td>
                        <td>{{ $entry->created_at }}</td>
                    </tr>
                @endforeach
            </tbody>
        </table></div></section>
    @endif
    <x-pagination-links :paginator="$history" />
</x-layouts.admin>
